#!/bin/bash

# constants
readonly SCRIPT_DIR=$(cd $(dirname $0) && pwd)
readonly SETUP_FILES_DIR=$SCRIPT_DIR/rails_new_files
readonly APP_NAME=$1
readonly RAILS_VERSION=5.2.1
readonly RUBY_VERSION=$(rbenv global)

# app directory
mkdir $APP_NAME
cd $APP_NAME

# rails new
sed s/RAILS_VERSION/$RAILS_VERSION/g $SETUP_FILES_DIR/Gemfile_rails_new > Gemfile
rbenv local $RUBY_VERSION
bundle install
bundle exec rails new . --force --skip-test-unit ${@:2} || exit

# git initial commit
git add .
git commit -m 'chore: create rails application.'

# append gems
cat $SETUP_FILES_DIR/Gemfile_gems >> Gemfile
bundle install

# simple_form
bin/rails generate simple_form:install --bootstrap
cp $SETUP_FILES_DIR/minimal_form_builder.rb lib
cp $SETUP_FILES_DIR/minimal_form_helper.rb app/helpers

# kaminari
bin/rails generate kaminari:views bootstrap4 -e haml

# rspec
bin/rails generate rspec:install
bundle exec spring binstub rspec
cp $SETUP_FILES_DIR/.rspec ./
rm -rf test

# haml-rails
HAML_RAILS_DELETE_ERB=true bin/rails haml:erb2haml <<-EOF
y
EOF

# application.sass
cp $SETUP_FILES_DIR/application.sass app/assets/stylesheets
rm -f app/assets/stylesheets/application.css

# application.coffee
cp $SETUP_FILES_DIR/application.coffee app/assets/javascripts
rm -f app/assets/javascripts/application.js

# time_formats
cp $SETUP_FILES_DIR/time_formats.rb config/initializers

# deploy sample page
bin/rails generate controller samples index --no-helper --no-assets --no-controller-specs --no-view-specs --no-helper-specs
cp -f $SETUP_FILES_DIR/index.html.haml app/views/samples

# TODO
echo ==============================
cat $SETUP_FILES_DIR/TODO.md
echo ==============================
