#!/bin/bash

# variables
app_name=$1
rails_version=5.2.1
ruby_version=$(rbenv global)

# app directory
mkdir $app_name
cd $app_name

# files
cat << EOG > Gemfile
source "http://rubygems.org"
gem "rails", "$rails_version" #利用するバージョンを指定する
EOG
rbenv local $ruby_version

# bundle
bundle install
bundle exec rails new . --force ${@:2}
